db-uri = "postgres://authenticator:localdev_authenticator_password@postgres:5432/traffic_data"
db-schemas = "api"
db-anon-role = "web_anon"
jwt-secret = "super-secret-admin-key-for-local-dev-32"
openapi-mode = "follow-privileges"
server-port = 3000
